# On indique ici la version de docker-compose
version: '3.3'

# Ici on liste l'ensemble des services (les containers)
services:

  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    command: --default-authentification-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm
      MYSQL_PASSWORD: database_password
    volumes:
      - mariadbData:/var/lib/mysql
    restart: always

  espocrm:
    image: nrameloclock/espocrm
    container_name: espocrm
    ports:
      - 81:80
    environment: 
      ESPOCRM_DATABASE_HOST: mariadb
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: database_password
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
    volumes:
      - espocrmData:/var/www/html
    restart: always
    links:
      - mariadb:mariadb

volumes:
  mariadbData: 
  espocrmData: